export const KEYS = {
  BOOK_MARK: 'book_mark',
  BOOK_MARK_CREATE: 'book_mark_create',
  BOOK_MARK_UPDATE: 'book_mark_UPDATE',
  BOOK_MARK_DELETE: 'book_mark_DELETE',
  FOLDER: 'folder',
  FOLDER_DELETE: 'folder_delete',
  FOLDER_UPDATE: 'folder_update',
  FOLDER_CREATE: 'folder_create',
  ROW: 'row',
  ROW_RANDOM: 'row_random',
  ROW_CREATE: 'row_create',
  ROW_DELETE: 'row_delete',
  ROW_UPDATE: 'row_update',
  NOTIFICATION: 'notificatio',
  NOTIFICATION_CREATE: 'notificatio_create',
  NOTIFICATION_DELETE: 'notificatio_delete',
}
