/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as FolderIdBookMarkIdTestingImport } from './routes/folder/$id/$bookMarkId/testing'
import { Route as FolderIdBookMarkIdRowsImport } from './routes/folder/$id/$bookMarkId/rows'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FolderIdBookMarkIdTestingRoute = FolderIdBookMarkIdTestingImport.update({
  path: '/folder/$id/$bookMarkId/testing',
  getParentRoute: () => rootRoute,
} as any)

const FolderIdBookMarkIdRowsRoute = FolderIdBookMarkIdRowsImport.update({
  path: '/folder/$id/$bookMarkId/rows',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/folder/$id/$bookMarkId/rows': {
      preLoaderRoute: typeof FolderIdBookMarkIdRowsImport
      parentRoute: typeof rootRoute
    }
    '/folder/$id/$bookMarkId/testing': {
      preLoaderRoute: typeof FolderIdBookMarkIdTestingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FolderIdBookMarkIdRowsRoute,
  FolderIdBookMarkIdTestingRoute,
])

/* prettier-ignore-end */
